# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the neoforge loader
loaderVersion="[4,)" #mandatory

# The license for your mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# If your mod is purely client-side and has no multiplayer functionality, set this to true
#clientSideOnly=true #optional - defaults to false if absent

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}" #mandatory
# The version number of the mod
version="${mod_version}" #mandatory
# A display name for the mod
displayName="${mod_name}" #mandatory
# A text field displayed in the mod UI
authors="${mod_authors}" #optional
# A text field displayed in the mod UI
#credits="" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.runic]] #optional
modId="neoforge" #mandatory
mandatory=true #mandatory
versionRange="[21.1,)" #mandatory (NeoForge 1.21.1+)
ordering="NONE"
side="BOTH"

# Here's another dependency
[[dependencies.runic]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]" # match the exact Minecraft version
ordering="NONE"
side="BOTH"

# Features are specific properties of the game environment that your mod requires
#[features.${mod_id}]
#openGLVersion="[3.2,)"
